# for hosting in Google Cloud Plattform 
runtime: custom
env: flex
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app

automatic_scaling:
   min_num_instances: 1
   max_num_instances: 1

resources:
   cpu: 1
   memory_gb: 2
   disk_size_gb: 1